### ISSUE TITLE
Option to show only what's in appnames.txt is missing in the latest release (works in the prior one, 0.4)

### ISSUE THREAD

**Issue by wysie** [tverona1/QuestAppLauncher#13]
As per subject, that option is missing now.

**Comment by wysie** [comment]
Thanks for looking into this

**Comment by tverona1** [comment]
I removed this option when I added support for custom tabs: You can turn off auto-tabs and define custom tabs in appnames.txt, effectively achieving the same thing. Have you tried that?

**Comment by wysie** [comment]
Hello, yup I figured. I'm doing that, but the issue is there's still an
"All" tab that shows everything. Just being picky to be honest. Thanks for
the hard work on this!

**Comment by tverona1** [comment]
Ok :). I"m going to close this issue then given the above works for you.

Also, note that you can hide apps by pressing B or Y.
