### ISSUE TITLE
App does not appear

### ISSUE THREAD

**Issue by tedwaltmuf** [tverona1/QuestAppLauncher#18]
Im trying to launch an android vr app from the google play store but I cannot find it in the launcher.

**Comment by tverona1** [comment]
can you provide more details? which app is it?

**Comment by tedwaltmuf** [comment]
Vf 2000 on google play

**Comment by tverona1** [comment]
@tedwaltmuf, can you go to settings (the gear icon in the top left) and enable "2d apps"? Let me know if it shows up. By default, 2d apps are hidden. (I just tried it with this app)

**Comment by tedwaltmuf** [comment]
I did and it’s not supposed to be 2d it’s a vr app. It does not show up still.

**Comment by tverona1** [comment]
Hi @tedwaltmuf  - I installed the app and it shows up as 2d (under the 2d tab). The launcher checks for a specific manifest setting to determine if this is an Oculus 3d app ("com.samsung.android.vr.application.mode"). This app does not contain this setting.

**Comment by tedwaltmuf** [comment]
Is there a way to change it because it is a vr app that works on Samsung gear normally

**Comment by tverona1** [comment]
Are you sure that this is a VR app? When I launch it on my Quest, it runs as a 2D app. Here's the documentation for VR apps, which describes the above manifest setting: https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-native-manifest/

**Comment by tedwaltmuf** [comment]
Yes I can use it on a Samsung gear, I’m trying to port it over to the oculus because I do not like the gear. There’s the vf2000 which is vr portion and it has another app that acts as the controller from a tablet called vf2000 controller.

**Comment by tverona1** [comment]
Just to clarify: On my quest, vf2000 runs as up as a 2d app. Is that the same for you?

**Comment by tedwaltmuf** [comment]
Yes I can only see it on the side quest launcher in my quest and when I load it is only in 2d and it doesn’t register with the headset tracking.

**Comment by tverona1** [comment]
Ok - so that's not an issue with quest app launcher; the app itself runs as 2d on the quest. If you enabled "Show 2D" in settings, does it show up under the 2D tab?

**Comment by tedwaltmuf** [comment]
It seems to show up now after selecting show 2d and a restart. Is there anyway to make it play how it’s supposed to in vr?

**Comment by tverona1** [comment]
Thanks for confirming. I'm going to close this issue because it's not an issue with the launcher. I think you'll need to contact the developers of this app and ask them to port it to Quest.
