### ISSUE TITLE
Separate tabs for Quest, Go, Android

### ISSUE THREAD

**Issue by ANewDawn** [tverona1/QuestAppLauncher#2]

**Comment by fecheva** [comment]
My vote for this. Maybe classification may be done automatically, anyway I think it may also be useful to allow sections in the appnames.txt. The one I prepared has intentionally been ordered that way: 1st Store Native Questm; 2nd Sideloadable Native Quest; 3rd, Go/GearVR.

It may be a generalization to allow defining sections to be mapped into tabs. That way, users may choose what kind of classifications to use (ie. by genre: horror, adventure, racing)

**Comment by tverona1** [comment]
Done - see readme
