### ISSUE TITLE
How to change names and thumbnails ? 

### ISSUE THREAD

**Issue by bysty666** [tverona1/QuestAppLauncher#21]
Thank you for this app.  But where is explication for change name and thumbnails ? i don't found nowhere.

**Comment by tverona1** [comment]
Hi @bysty666 - can you explain what you are trying to do? Have you already downloaded the app names & icons (from settings pick "Update now").

Or, are you trying to rename an app (pick a different app name + icon)?

**Comment by tverona1** [comment]
Added support for renaming app. To be released as v0.10

**Comment by bysty666** [comment]
I don't understand if it's possible to change name and icon for thumbnails.  Possible in 0.10 ?

**Comment by tverona1** [comment]
Yes, highlight the app you want to rename and press X or B. It will then give you a list of available apps to choose from.

**Comment by bysty666** [comment]
haaa very good thanks ^^  and there is thumbnail inside ?

**Comment by tverona1** [comment]
Yes - basically it takes you to another grid view with the possible apps to choose from. Give it a try and let me know what you think.

**Comment by bysty666** [comment]
i tried, but when i push B, icon is hiding.  i tried to uninstall and reinstall but same problem

**Comment by tverona1** [comment]
Sorry, try pressing A, not B

**Comment by bysty666** [comment]
Maybe i forgot something because nothing happen when i push A button.

**Comment by tverona1** [comment]
Are you on version 0.10?

**Comment by bysty666** [comment]
where could i see the version ?   i install from sidequest, i uninstall then after install with "install latest" but ... i think there is a problem with install and maybe i stay in old version

**Comment by tverona1** [comment]
Try from here: https://github.com/tverona1/QuestAppLauncher/releases/download/v0.10/QuestAppLauncher.apk

**Comment by bysty666** [comment]
ok, i understand my mistake, it was because i launch via "in within" i though it must be launch by this way.

**Comment by tverona1** [comment]
Ah ok. Does it work now for you with renaming?

**Comment by bysty666** [comment]
it"s ok by "unknown application"   :)   but do you work for something launch directly from our library ?

**Comment by bysty666** [comment]
yes by this way everything is ok  !   thank you

**Comment by tverona1** [comment]
Great!

**Comment by tverona1** [comment]
You'd have to respoof with latest version if you want to launch from home screen.

**Comment by bysty666** [comment]
what is ...respoof ?   sorry

**Comment by tverona1** [comment]
If you're on the discord, can you ping me there (username is chodaboy)? Thanks

**Comment by bysty666** [comment]
Hello, i don't found your nickname on discord, mine : bysty#6070   Thanks
