### ISSUE TITLE
About the game application Chinese display problem

### ISSUE THREAD

**Issue by androbama** [tverona1/QuestAppLauncher#24]
After many tests (0.8/0.9/0.91/0/10), it seems that up to 20 Chinese game application names can be displayed. More than 20 will display garbled characters, or the Chinese name cannot be displayed completely. For what reason, please fix it. ?

**Comment by tverona1** [comment]
Thanks for reporting this. So after 20 or so Chinese apps installed, the characters on the existing Chinese apps (that used to display fine when < 20 were installed) now start to be garbled?

**Comment by androbama** [comment]
Yes

**Comment by tverona1** [comment]
Fixed in v0.10.1
