### ISSUE TITLE
Another assets update 

### ISSUE THREAD

**Issue by NewsGuyTor** [tverona1/QuestAppLauncher#28]
I've begun to maintain an updated fork of the assets repo here:
https://github.com/NewsGuyTor/QuestAppLauncher_Assets

I've also added an updated release containing the latest assets here:
https://github.com/NewsGuyTor/QuestAppLauncher_Assets/releases/tag/10%2F12%2F2019 . Feel free to push it to your users :)

**Comment by tverona1** [comment]
Thanks - I've started to use a scripting tool to upload assets. I've just updated to latest assets. Please refresh & check if you see the latest.

**Comment by kristofferR** [comment]
So just go confirm, are you pulling the assets from my efforts or somewhere else? Should I keep updating my repo?

**Comment by tverona1** [comment]
I'm using a separate tool to update all the quest assets, so it doesn't have to be done manually. I just need to remember to update :)
