### ISSUE TITLE
Stops sorting/showing Apps with Quill Theater installed

### ISSUE THREAD

**Issue by gunnarweibrink** [tverona1/QuestAppLauncher#29]
Hi,

my first post in here... many thank's for your fantastic app!

The problem:
- occurs with 0.10 and 0.10.1
- after installing free "Quill Theater" with AppID 'com.facebook.arvr.quillplayer'
- your app stops "sorting" after "Q" (in  my case "Quake2Quest" or 'com.drbeef.quake2quest'
- it doesn't matter if you sort by name or recent
- with deinstalling "Quill Theater" the problem is gone

Maybe you could implement a fix?
Thx in advance!

Gunnar

**Comment by tverona1** [comment]
Thanks for reporting this! Release v0.10.2 fixes this issue.

**Comment by gunnarweibrink** [comment]
Wow, that was blistering fast... thank you!
