### ISSUE TITLE
Launcher does not respect hand tracking settings

### ISSUE THREAD

**Issue by hybridherbst** [tverona1/QuestAppLauncher#31]
Quest supports hand tracking now.
Apps that use it specify hand tracking capabilities on the manifest. When hand tracking is enabled and an app does not support it, a popup asks to disable it.
Now, QuestAppLauncher does not respect that setting; when launching apps that support hand tracking through it the popup still appears.
Expected: app launches
Actual: app does not launch, asks to disable hand tracking

Launching from "unknown sources" works fine.

Example: https://sdq.st/a-506

**Comment by tverona1** [comment]
Added hand tracking support with latest release (v0.11). Please try it :)
