### ISSUE TITLE
Hand tracking support

### ISSUE THREAD

**Issue by Ladypoly** [tverona1/QuestAppLauncher#34]
I updated oculus integration to v14 and enabled hand tracking.
Tracking is working fine but (of cause) it's not implemented for the raycast on the hand pointer pose and the click on pinch.
Unfortunately I'm not a programmer. I mostly just play a around with node based scripting tools.
If someone could implement hand tracking controls that would be so awesome.
I could build the launcher than with my licence without splash screen for sidequest

**Comment by Bluscream** [comment]
yeah please add this atleast partially <3

**Comment by tverona1** [comment]
Added hand tracking support with latest release (v0.11) :)

**Comment by Bluscream** [comment]
Oh my God
you're a hero <3
