### ISSUE TITLE
Add feature: generate current 'Appnames' from current status

### ISSUE THREAD

**Issue by korenmic** [tverona1/QuestAppLauncher#35]
Imagine having over 200 apps made of: official oculus store apps, indie vr games and regular android 2d apks.

Manually creating the initial Appnames.txt or Appnames.json would be a huge pain as the my only way (currently) of creating it is to manually click the Gear icon of every app under the sidequest's "Currently installed apps" view and copying the package and app name from it using the mouse to have something to fill just one record, and then manually repeating this at least 200+ times.

If it would be possible to click on a button on the app launcher and generate to current Appnames state to a file, it would be significantly easier for users to start managing and editing it.

**Comment by tverona1** [comment]
@korenmic - this doesn't seem like a feature that should be built into the launcher but rather something that can be done externally to it. It's fairly easy to write a python program that invokes adb and returns the list of installed apps. Here's a bit of code that does something like this - process_adb_apks() return a dictionary of apk information. I'm sure there are external tools that do something similar.

```
# Build the set of Quest apks, including package and version info
def process_adb_apks():
    adb_apks = {}
    package_name_list = adb_get_apk_list()
    for package_name in package_name_list:
        apk_info = adb_get_apk_info(package_name)
        adb_apks[apk_info['package_name']] = apk_info
    return adb_apks

# Launch executable and return output
def launch_executable(args, bin_path):
    try:
        output = subprocess.check_output([bin_path] + args, stderr=subprocess.STDOUT)
        return output.decode(sys.stdout.encoding)
    except subprocess.CalledProcessError as e:
        raise Exception(str.format(str(e) + ". Output: '%s'" % (e.output.decode(sys.stdout.encoding).rstrip()))) from e
    except Exception as e:
        raise type(e)(str.format(str(e) + " when calling '%s'" % (bin_path)))

# ADB functions
def adb(args, adb_path=None):
    if (adb_path is None):
        # If path is not specified, assume it is in bin directory relative to script location
        adb_path = os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])), 'bin/adb.exe')
    return launch_executable(args, adb_path)

def adb_get_apk_list():
    adb_apk_list = []
    output = adb(['shell', 'cmd', 'package', 'list', 'packages', '-3'])
    package_names = re.compile("package:(\\S+)").findall(output)
    return package_names

def adb_get_apk_info(package_name):
    output = adb(['shell', 'dumpsys', 'package', package_name])
    match = re.compile("versionCode=(\\d+)").search(output)
    if not match:
        raise Exception(str.format("error getting versionCode: %s" % (output)))
    version_code = match.group(1)
    match = re.compile("versionName=(\\S+)").search(output)
    if not match:
        raise Exception(str.format("error getting versionName: %s" % (output)))
    version_name = match.group(1)
    return {
        'package_name': package_name,
        'version_code': version_code,
        'version_name': version_name
    }
```

**Comment by korenmic** [comment]
Indeed I agree with you, after some thought I came to the same conclusion
and decided to do just that - https://github.com/korenmic/quest-package-categorizer

wish I had updated it here earlier :)

**Comment by tverona1** [comment]
that's awesome! i wonder if there is a way to get standard category names from oculus store or from sidequest and auto-generate the categories.

**Comment by korenmic** [comment]
I actually talked with sidequest on their discord, asking if they were willing to share some apis to help getting the actual app names (or any other information) of sq-installable packages and unfortunately they said that currently no.

Its only a pain when I have to get the apps names for the **first** time I do it (when I have to deal with the hundreds of unnamed packages), but if I install only one new app every week, its not such a big deal to manually update the json just for that one single app every time.
