### ISSUE TITLE
files appsnames.[txt/json] are completely ignored

### ISSUE THREAD

**Issue by korenmic** [tverona1/QuestAppLauncher#36]
in the readme it is claimed that files:
/sdcard/Android/data/aaa.QuestAppLauncher.App/files/appsnames.[txt/json]

with the relevant format accordingly

should overwrite "Custom Tabs"

but in fact they do not, while app is running all I can see (of "Custom Tabs") is "ALL"

**Comment by korenmic** [comment]
how can I still make this happen despite the bug?

must I recreate this entire path of my own git repo
https://github.com/tverona1/QuestAppLauncher_Assets/releases/latest
(since it appears in config.json:
```
  "downloadRepos": [
    {
      "repoUri": "tverona1/QuestAppLauncher_Assets/releases/latest",
      "type": "github"
    }
```
)
and make sure that this appsnames.json contains the data I want?

https://github.com/tverona1/QuestAppLauncher_Assets/releases/download/v03.14.2020/appnames_quest.json

**Comment by Erteje** [comment]
> how can I still make this happen despite the bug?
> 
> must I recreate this entire path of my own git repo
> https://github.com/tverona1/QuestAppLauncher_Assets/releases/latest
> (since it appears in config.json:
> 
> ```
>   "downloadRepos": [
>     {
>       "repoUri": "tverona1/QuestAppLauncher_Assets/releases/latest",
>       "type": "github"
>     }
> ```
> 
> )
> and make sure that this appsnames.json contains the data I want?
> 
> https://github.com/tverona1/QuestAppLauncher_Assets/releases/download/v03.14.2020/appnames_quest.json


Edit "**appnames.json**" with your apps, and then upload in to "**files**" folder. Withot S "no app**s**name"

Example:

`{"com.vertigogames.azsq": {"category": "Shots", "name": "Arizona Sunshine"}, "com.Oculus.FirstContact": {"category": "First Time", "name": "First Contact VR"}}`

Or, with two category (or tab):

`{"com.vertigogames.azsq": {"category": "Shots", "category2": "Favourites", "name": "Arizona Sunshine"}, "com.Oculus.FirstContact": {"category": "First Time", "name": "First Contact VR"}}`

**Comment by tverona1** [comment]
Hi @korenmic - I can't repro this issue. I grabbed your file (from https://raw.githubusercontent.com/korenmic/quest-package-categorizer/master/appnames_all.json) and copied it to sdcard/Android/data/aaa.QuestAppLauncher.App/files. I relaunched quest app launcher and your custom categories showed up correctly. So it seems to work correctly for me. I'm not sure why it is not working for you.

@Erteje if you have a chance, maybe you can also try Michael's file above?

**Comment by Erteje** [comment]
> Hi @korenmic - I can't repro this issue. I grabbed your file (from https://raw.githubusercontent.com/korenmic/quest-package-categorizer/master/appnames_all.json) and copied it to sdcard/Android/data/aaa.QuestAppLauncher.App/files. I relaunched quest app launcher and your custom categories showed up correctly. So it seems to work correctly for me. I'm not sure why it is not working for you.
> 
> @Erteje if you have a chance, maybe you can also try Michael's file above?

Thanks @tverona1. Yes, it is the same code, but I wanted to customize it according to my preferences, because I do not want so many categories. 
Thank you anyway.

**Comment by korenmic** [comment]
Correct, my mistake probably had a typo. the appnames.json works in the correct path now. no idea why it did not before.

**Comment by Erteje** [comment]
👍

**Comment by tverona1** [comment]
cool! good to hear it is working!

**Comment by tverona1** [comment]
Just replied to your review on side quest too - I've been neglecting the review comments :).
