### ISSUE TITLE
Change App name to appear first in unknown sources

### ISSUE THREAD

**Issue by korenmic** [tverona1/QuestAppLauncher#50]
In previous oculus quest versions, the unknown sources section was sorted by `package name`
since the `package name` of QuestAppLauncher is
`aaa.QuestAppLauncher.App`
this was extremely beneficial, since despite the huge amount of apps installed that are listed under unknown sources
this app was always the first, and it was used to efficiently find other apps easily using the categories feature (which is great!)

But unfortunately, now due to recent updates, oculus quest forces the sort to be based on the `app name` instead of the `package name`
This is bad because the app name starts with the `letter Q`, and it means quite a lot of scrolling and searching before we even get to the stage where we can start launching the app (especially for people with a lot (a lot!) of unknown sources apps installed such as myself)
and maybe after the few minutes of scrolling I already found the installed app I was originally interested in searching and launching (using the categories help of QuestAppLauncher)

and now although its still very useful, the whole process of quitting one app, spending a lot of time searching for the quest app launcher, and launching another app
takes significantly more time and is much less efficient (compared to before, few seconds, few clicks, QuestAppLauncher was always first and easy to find).

Can we convince facebook to allow multiple types of `sort` to bring back the sort by `package name` by default?
maybe
But can this issue be prevented right now? by prefixing `0` or `aaa` to the app name? I believe so!

I like the name you chose for your app, and I wouldn't suggest changing it unless it wouldn't effect greatly the whole experience.

**Comment by tverona1** [comment]
Fixed in v0.11.1

**Comment by VRthumbnailsFolders** [comment]
Hello.
On my Quest 2, the app is not positioned first!
An idea of the problem ?
